import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Sidebar() {
    return (
        <aside className="w-72 flex-shrink-0 h-screen overflow-hidden bg-neutral-900 border-r border-neutral-800 text-neutral-100">
            <div className="p-6 flex items-center gap-3 border-b border-neutral-800">
                <div className="size-12 rounded-full bg-neutral-700" />
                <div className="flex flex-col">
                    <span className="font-semibold">Lukáš Čeč</span>
                    <span className="text-xs text-neutral-400">@handle</span>
                </div>
            </div>

            <nav className="p-3">
                <ul className="space-y-1">
                    {["Home", "About", "Achievements", "Projects", "Dashboard", "Chat Room", "Contact"].map(
                        (item) => (
                            <li key={item}>
                                <a
                                    href="#"
                                    className="flex items-center justify-between px-3 py-2 rounded-lg text-sm duration-200 hover:bg-neutral-800/80"
                                >
                                    <span>{item}</span>
                                    <span className="text-neutral-500">→</span>
                                </a>
                            </li>
                        )
                    )}
                </ul>
            </nav>

            <div className="mt-auto p-3">
                <button className="w-full rounded-xl border border-emerald-700 bg-emerald-900/30 px-4 py-2 text-sm">
                    Smart Talk
                </button>
            </div>

            <footer className="p-3 text-xs text-neutral-500 border-t border-neutral-800">
                COPYRIGHT © {new Date().getFullYear()}<br /> Lukáš Čeč. All rights reserved.
            </footer>
        </aside>
    );
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="h-full">
        <body className="h-full bg-neutral-950 text-neutral-200 antialiased">
        <div className="flex h-screen overflow-hidden">
            <Sidebar />
            <main className="flex-1 h-screen overflow-y-auto">
                <div className="mx-auto max-w-5xl px-6 py-10">{children}</div>
            </main>
        </div>
        </body>
        </html>
    );
}

